sudo: false
language: php
php:
  - 5.4
install:
  - composer install
script:
  - bin/phpunit
# http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
cache:
  directories:
    - vendor
    - $HOME/.composer/cache